# Travis-CI Build for the OpenRA website
# see travis-ci.org for details

language: ruby

env:
  global:
    secure: "g0ObdYxcbfkLzSNmyhYN+74qHsGEg3mwt9e0tZLnmCwISL8qSErjHz+t46Jdyw4hXrQ63kXnCQApIqbtiPywXyKgMzINhXTnzuYbXc4wfrSz900xBw/eCKTICJO+DcwHgwE/RUbQzAB0a/lc6Y49YTr7ez9i2Uv1ecQ/Wo0Mcpo="

install:
 - gem install builder kramdown octokit uglifier
 - gem install nanoc --version 3.6.9

script:
 - nanoc compile

after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./update-github-pages.sh

# Only watch the production branch.
branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
