# Travis-CI Build for the OpenRA website
# see travis-ci.org for details

language: ruby

env:
  global:
    secure: "XF0bBT03kB2mITedNssEdEizz2/30Miw9N1S/VPLupgi42DTcbcIAvOUSV6XdLaKrcdZ900x1v8w0Ol23lkz1RTmnVDg4B90uvjnpcYW/fAr5/3775/ZFh4B1724Hw4y0kMGHgZPOHItYoju9akSICaRw3/2wP+6ttFFVrSAX70="

install:
 - gem install builder kramdown octokit uglifier
 - gem install nanoc --version 3.6.9

script:
 - nanoc compile

after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./update-github-pages.sh

# Only watch the production branch.
branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
